# Updated Playbook for R1soft Agent Installation on CentOS, RedHat, Fedora, Debian and Ubuntu systems

---
- name: R1soft agent installation on new servers
  hosts: all
  connection: ssh

# For Fedora,Debian and Ubuntu OS do manually install python package to enable ansible to connect with the systems. To automate the process using ansible by running the following play for Debian and Ubuntu systems:
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
    - setup: # aka gather_facts

#the above code turns of fact gathering as it requires python installed and sets up a pre-task to run before all others in the playbook. It then checks if python 2.7 is installed and if not then it installs it. registers the output if installation is needed and then prints it to the terminal output.

  tasks:
    - name: Create Repo file
      when: ansible_os_family == "RedHat"
      copy:
        src: /etc/yum.repos.d/r1soft.repo
        dest: /etc/yum.repos.d/r1soft.repo
        owner: root
        group: root

    - name: Install Agent
      when: ansible_os_family == "RedHat"
      package:
        name: serverbackup-enterprise-agent
        state: installed

    - name: Get Key From Server
      when: ansible_os_family == "RedHat"
      command: "serverbackup-setup --get-key http://ip.ahmed.80:80"
    - name: Restart R1soft Agent
      when: (ansible_distribution == "CentOS" and  ansible_distribution_major_version == "6")

      service:
        name: cdp-agent
        state: restarted
    - name: Restart R1soft Agent
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
      systemd:
        name: sbm-agent
        state: restarted


    - name: Create Repo file
      when: ansible_distribution == "Fedora"
      copy:
        src: /etc/yum.repos.d/r1soft.repo
        dest: /etc/yum.repos.d/r1soft.repo
        owner: root
        group: root


    - name: Install Agent
      when: ansible_distribution == "Fedora"
      package:
        name: serverbackup-enterprise-agent
        state: installed


    - name: Get Key From Server
      when: ansible_distribution == "Fedora"
      command: "serverbackup-setup --get-key http://ip.ahmed.80:80"


    - name: Restart R1soft Agent
      when: ansible_distribution == "Fedora"
      service:
        name: cdp-agent
        state: restarted





    - name: Install r1soft on Ubuntu
      when: ansible_distribution == "Ubuntu"
      command: "echo deb http://repo.r1soft.com/apt stable main >> /etc/apt/sources.list"

 - name: Next command
      when: ansible_distribution == "Ubuntu"
      get_url:
        url: http://repo.r1soft.com/r1soft.asc
        dest: /tmp

    - name: Next command
      when: ansible_distribution == "Ubuntu"
      command: "apt-key add /tmp/r1soft.asc"


    - name: Next command
      when: ansible_distribution == "Ubuntu"
      command: "apt-get update"


    - name: install agent
      when: ansible_distribution == "ubuntu"
      apt:
        name: serverbackup-enterprise-agent
        state: present


    - name: Get Key From Server
      command: "serverbackup-setup --get-key http://ip.ahmed:80"



    - name: Install r1soft on Debian
      when: ansible_distribution == "Debian"
      command: "echo deb http://repo.r1soft.com/apt stable main >> /etc/apt/sources.list"

    - name: Next command
      when: ansible_distribution == "Debian"
      get_url:
        url: http://repo.r1soft.com/r1soft.asc
        dest: /tmp

    - name: Next command
      when: ansible_distribution == "Debian"
      command: "apt-key add /tmp/r1soft.asc"

 - name: Next command
      when: ansible_distribution == "Debian"
      command: "apt-get update"


    - name: install agent
      when: ansible_distribution == "Debian"
      apt:
        name: serverbackup-enterprise-agent
        state: present


    - name: Get Key From Server
      command: "serverbackup-setup --get-key http://ip.ahmed:80"
      
